# Generated by Django 5.1 on 2024-08-22 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bazon', '0004_saledocument_amo_lead_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburl', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('bazon_accounts', models.ManyToManyField(related_name='amo_accounts', to='bazon.bazonaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amo_id', models.IntegerField()),
                ('bazon_id', models.IntegerField(blank=True, null=True)),
                ('amo_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='amo.amoaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amo_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('bazon_status', models.CharField(blank=True, choices=[('NEW', 'Новый'), ('WORK', 'В работе'), ('ISSUED', 'Выданные'), ('NOT_IMPLEMENTED', 'Не реализованные')], max_length=20, null=True)),
                ('amo_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='amo.amoaccount')),
            ],
        ),
    ]
