# Generated by Django 5.1 on 2024-08-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amoaccount',
            name='token',
        ),
    ]
