# Generated by Django 5.1 on 2024-08-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0002_remove_amoaccount_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='amoaccount',
            name='token',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
