# Generated by Django 5.1 on 2024-08-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazonaccount',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bazonaccount',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
