# Generated by Django 5.1 on 2024-08-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazon', '0005_contractor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractor',
            old_name='balance_reverse',
            new_name='balance_reserve',
        ),
    ]
