# Generated by Django 5.1 on 2024-08-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bazon", "0006_rename_balance_reverse_contractor_balance_reserve"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractor",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="contractor",
            name="type",
            field=models.CharField(max_length=50),
        ),
    ]
