name: CI/CD Pipeline
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /root/amo_bazon
            git pull origin master
            docker compose down
            docker compose pull
            docker compose up -d --build
            
            # Ожидание запуска контейнера Django
            max_attempts=10
            attempt=0
            container_name=amo_bazon-django-1

            until [ $attempt -ge $max_attempts ]; do
              if [ $(docker ps -q -f name=$container_name) ]; then
                echo "Контейнер Django запущен успешно"
                break
              fi
              echo "Ожидание запуска контейнера Django..."
              sleep 10
              attempt=$((attempt + 1))
            done

            # Проверка статуса контейнера после ожидания
            if [ $attempt -eq $max_attempts ]; then
              echo "Контейнер Django не запустился, отменяю изменения"
              git reset --hard HEAD
              exit 1
            fi